source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SSDataSources-YapDB_Example', :exclusive => true do
  pod 'SSDataSources-YapDB', :path => '../'
end

target 'SSDataSources-YapDB_Tests', :exclusive => true do
  pod 'SSDataSources-YapDB', :path => '../'

  
end
